spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.42.134:3309/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.42.134:3308/test
      username: root   # 只读账户
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.42.134:3305/test
      username: root   # 只读账户
      password: root
      driver-class-name: com.mysql.jdbc.Driver